version: 0.1
log:
  fields:
    service: registry
# auth:
#   token:
#     realm: https://0.0.0.0:5001/api/auth
#     service: registry
#     issuer: sergbelom
#     rootcertbundle: /certs/myregistry.crt
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
notifications:
    endpoints:
      - name: alistener
        url: http://172.16.1.3:8086/log
        headers:
            Authorization: [Bearer <your token, if needed>]
        timeout: 500ms
        threshold: 5
        backoff: 1s
