version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
# token:
#   issuer: "sergbelom"
#   expiration: 900
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
notifications:
  events:
    includereferences: true
  endpoints:
    - name: alistener
      disabled: false
      url: http://172.16.1.3:8086/log
      headers:
          Content-Type:
            - application/json
          #Authorization: [token]
      timeout: 1s
      threshold: 10
      backoff: 1s
      ignoredmediatypes:
        - application/octet-stream
      # ignore:
      #   mediatypes:
      #      - application/octet-stream
# notifications:
#     endpoints:
#       - name: alistener
#         url: http://172.16.1.3:8086/log
#         headers:
#             Authorization: [Bearer token]
#         timeout: 500ms
#         threshold: 5
#         backoff: 1s
