version: "3"

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: https://0.0.0.0:5001/api/auth
      REGISTRY_AUTH_TOKEN_SERVICE: localhost
      REGISTRY_AUTH_TOKEN_ISSUER: sergbelom
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/STS_docker_auth.crt
    volumes:     
      - ${PWD}/certs:/certs
      - ${PWD}/config.yml:/etc/docker/registry/config.yml
      - ${PWD}/registry-storage:/var/lib/registry
    networks:
      - sts-net   
    depends_on:
      - sts_docker_auth

  sts_docker_auth:
    restart: always
    image: sergbelom/sts_docker_auth
    container_name: sts_docker_auth
    networks:
      - sts-net
    ports:
    - "5001:5001"
    volumes:
      - ${PWD}/certs:/certs
      - ${PWD}/auth_log:/auth_log

  sts_listener_server:
    restart: always
    image: sergbelom/sts_listener_server
    container_name: sts_listener_server
    networks:
      - sts-net
    ports:
    - "8086:8086"
    volumes:
      - ${PWD}/listener_log:/listener_log
networks:
  sts-net:
